name: Build, Lint, and Test

on:
  push:
    branches: [master]
  pull_request:
  workflow_call:

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
      # maintenance LTS, active LTS and current version
        node-version: [18.x, 20.x, 21.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn test
      - name: Cache snap build
        if: ${{ matrix.node-version == '18.x' }}
        uses: actions/cache@v3
        with:
          path: ./packages/snap/dist
          key: snap-${{ runner.os }}-${{ github.sha }}
    
  e2e:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs:
      - build-lint-test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Restore snap build cache
        uses: actions/cache@v3
        with:
          path: ./packages/snap/dist
          key: snap-${{ runner.os }}-${{ github.sha }}
      - run: yarn install --immutable
      - name: Run unit tests
        run: yarn workspace @xrpl-snap/snap run test
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # e2e:
  #   name: End-to-end Tests
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build-lint-test
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version-file: '.nvmrc'
  #         cache: 'yarn'
  #     - name: Restore snap build cache
  #       uses: actions/cache@v3
  #       with:
  #         path: ./packages/snap/dist
  #         key: snap-${{ runner.os }}-${{ github.sha }}
  #     - run: yarn install --immutable
  #     - name: Install Google Chrome
  #       run: yarn install-chrome
  #     - name: Run e2e tests
  #       run: yarn workspace @xrpl-snap/snap run test

  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-latest
    needs:
      - build-lint-test
      - e2e
    steps:
      - run: echo "Great success!"
